/**
 * Questions d'amorce du chat (état vide) — 50 questions par chatbot, affichées
 * 3 par 3 avec rotation toutes les 30 secondes (décision Hugo, 2026-06).
 *
 * ⚠️ Module PUR et testable : aucune dépendance réseau, aucune donnée de santé
 * individuelle — uniquement des questions d'information générale.
 */
import type { ChatbotId } from '@/chat/chatContext';

/** Nombre de questions affichées simultanément. */
export const SUGGESTIONS_VISIBLE_COUNT = 3;

/** Intervalle de rotation des questions (ms). */
export const SUGGESTIONS_ROTATION_MS = 30_000;

export const STARTER_SUGGESTIONS: Record<ChatbotId, string[]> = {
  public: [
    'Que signifie une TSH élevée sur une prise de sang ?',
    "J'ai mal à la gorge depuis 3 jours, que faire ?",
    'Comment préparer ma consultation chez le cardiologue ?',
    'À quoi sert le médicament que je prends contre la tension ?',
    'Quels sont les effets secondaires fréquents du paracétamol ?',
    "Puis-je prendre de l'ibuprofène avec mon anticoagulant ?",
    "Comment lire les résultats d'une prise de sang ?",
    "Qu'est-ce qu'un taux de cholestérol LDL normal ?",
    'Pourquoi dois-je être à jeun pour certaines prises de sang ?',
    "Quels vaccins sont recommandés à l'âge adulte ?",
    'Comment soulager un rhume sans médicaments ?',
    "Quand consulter pour une fièvre chez l'adulte ?",
    "Qu'est-ce que l'hypertension artérielle exactement ?",
    "Comment savoir si je fais de l'apnée du sommeil ?",
    'Quelle est la différence entre un virus et une bactérie ?',
    'Les antibiotiques sont-ils utiles contre la grippe ?',
    'Comment fonctionne le dépistage du cancer colorectal ?',
    'À quel âge commencer les mammographies de dépistage ?',
    "Qu'est-ce que le diabète de type 2 ?",
    'Comment réduire mon taux de sucre dans le sang ?',
    'Pourquoi mon médecin me prescrit-il des statines ?',
    'Que faire en cas de piqûre de tique ?',
    "Comment reconnaître les signes d'un AVC ?",
    "Quels sont les symptômes d'une crise cardiaque chez la femme ?",
    "Mon enfant a de la fièvre : quand s'inquiéter ?",
    "Comment bien utiliser un inhalateur pour l'asthme ?",
    "Qu'est-ce que l'arthrose et comment la soulager ?",
    'Pourquoi ai-je des crampes nocturnes ?',
    'Quels aliments éviter avec un traitement anticoagulant AVK ?',
    "Un générique est-il aussi efficace que le médicament d'origine ?",
    "Comment conserver mes médicaments pendant l'été ?",
    "Que faire si j'ai oublié de prendre mon comprimé ?",
    "Qu'est-ce qu'une IRM et comment ça se passe ?",
    'Pourquoi mes analyses montrent-elles une ferritine basse ?',
    'Comment améliorer mon sommeil sans somnifères ?',
    "Quels sont les signes d'une carence en vitamine D ?",
    'La marche est-elle suffisante comme activité physique ?',
    'Comment arrêter de fumer : quelles aides existent ?',
    "Qu'est-ce que le reflux gastro-œsophagien ?",
    'Pourquoi ai-je souvent des maux de tête ?',
    "Quand faut-il s'inquiéter d'un grain de beauté ?",
    'Comment protéger ma peau du soleil efficacement ?',
    "Qu'est-ce qu'une infection urinaire et comment l'éviter ?",
    'Que penser des compléments alimentaires ?',
    'Comment se déroule une coloscopie ?',
    "Qu'est-ce que l'hypothyroïdie ?",
    'Pourquoi mon ordonnance limite-t-elle la durée du traitement ?',
    'Comment gérer le stress au quotidien ?',
    'Quels sont les premiers signes de la ménopause ?',
    'À quoi sert le vaccin contre le papillomavirus ?',
  ],
  student: [
    "Explique-moi la physiopathologie de l'insuffisance cardiaque",
    'Fais-moi un cours sur la pyélonéphrite aiguë (item 161)',
    'Quels sont les critères diagnostiques de la maladie de Horton ?',
    "Explique le mécanisme d'action des IEC et leurs effets indésirables",
    'Quelle est la démarche diagnostique devant une anémie microcytaire ?',
    "Décris la classification NYHA de l'insuffisance cardiaque",
    'Quels sont les critères de Light pour un épanchement pleural ?',
    'Explique la physiopathologie du diabète de type 1',
    'Comment interpréter une gazométrie artérielle ?',
    'Fais-moi une fiche sur la BPCO (item 209)',
    "Quels sont les signes ECG de l'infarctus du myocarde ?",
    'Explique le score de Glasgow et son utilisation',
    "Quelle est la prise en charge d'une céphalée aiguë brutale ?",
    'Décris les stades de la maladie rénale chronique',
    'Comment raisonner devant une hématurie macroscopique ?',
    'Explique la cascade de la coagulation simplement',
    'Comment différencier syndrome néphrotique et syndrome néphritique ?',
    "Fais-moi un cours sur la méningite bactérienne de l'adulte",
    'Quels sont les effets indésirables des corticoïdes au long cours ?',
    "Explique la physiopathologie de l'embolie pulmonaire",
    'Quelle est la conduite à tenir devant une hyperkaliémie ?',
    "Décris le bilan d'une HTA secondaire chez le sujet jeune",
    "Quels sont les critères DSM-5 de l'épisode dépressif caractérisé ?",
    "Explique le mécanisme des diurétiques de l'anse",
    'Comment interpréter un bilan hépatique perturbé ?',
    'Fais-moi une fiche comparative maladie de Crohn vs RCH',
    "Quels sont les signes de gravité d'une pneumonie (CRB65) ?",
    'Explique la physiopathologie de la cirrhose et ses complications',
    'Quelle est la démarche devant une hypercalcémie ?',
    'Décris les différents types de choc et leur profil hémodynamique',
    'Quels sont les critères de gravité de la pancréatite aiguë ?',
    "Explique l'axe hypothalamo-hypophyso-surrénalien",
    'Comment raisonner devant une polyarthrite débutante ?',
    'Fais-moi un cours sur le lupus érythémateux systémique',
    'Quels sont les signes radiologiques de la sarcoïdose ?',
    "Explique la physiopathologie de l'asthme",
    "Quelle est la prise en charge initiale d'un état de mal épileptique ?",
    'Décris la sémiologie du syndrome parkinsonien',
    'Quels examens devant une suspicion de sclérose en plaques ?',
    'Explique le métabolisme du fer et ses anomalies',
    'Comment interpréter une électrophorèse des protéines sériques ?',
    'Fais-moi une fiche sur les leucémies aiguës',
    "Quels sont les critères de gravité d'un paludisme ?",
    "Explique la physiopathologie de l'ulcère gastroduodénal",
    "Quelle est la démarche devant une protéinurie de découverte fortuite ?",
    'Décris les complications aiguës du diabète',
    'Quels sont les mécanismes des hyponatrémies ?',
    'Explique le dépistage de la trisomie 21 pendant la grossesse',
    'Comment raisonner devant une fièvre prolongée inexpliquée ?',
    "Fais-moi un cours sur l'hémostase primaire et ses explorations",
  ],
  professional: [
    'Anticoagulation en FA chez le sujet âgé insuffisant rénal ?',
    "Stratégie diagnostique devant une suspicion d'EP chez la femme enceinte",
    'Relais AVK → DOAC : modalités pratiques ?',
    'Cibles tensionnelles chez le diabétique selon les dernières recommandations ?',
    "Antibiothérapie probabiliste d'une pyélonéphrite à risque de BLSE ?",
    "Quand introduire un iSGLT2 dans l'insuffisance cardiaque à FEVG préservée ?",
    'Conduite à tenir devant une thrombopénie sous héparine ?',
    'Adaptation des doses de metformine selon le DFG ?',
    'Gestion périopératoire des antiagrégants plaquettaires ?',
    'Indications actuelles du dépistage du cancer du poumon ?',
    "Durée optimale d'anticoagulation après une TVP non provoquée ?",
    "Prise en charge d'une hyponatrémie chronique chez le patient âgé ?",
    'Stratégie thérapeutique dans la BPCO selon GOLD ?',
    'Quand suspecter une hypertension artérielle secondaire ?',
    "Bilan étiologique d'une fibrillation atriale de novo ?",
    "Antibiothérapie d'un érysipèle chez le patient allergique aux pénicillines ?",
    'Suivi biologique sous méthotrexate : quel rythme ?',
    'Corticothérapie dans la maladie de Horton : schéma de décroissance ?',
    "Indications de l'IRM cardiaque dans le bilan d'une myocardite ?",
    'Conduite à tenir devant un QT long médicamenteux ?',
    'Vaccinations chez le patient immunodéprimé : que recommander ?',
    "Prescription d'IPP au long cours : quels risques réels ?",
    'Statines en prévention primaire après 75 ans ?',
    "Bilan d'une hypercalcémie chez un patient sous thiazidiques ?",
    "Insulinothérapie basale : quand et comment l'initier en ville ?",
    'Quand demander une polysomnographie devant une HTA résistante ?',
    "Prise en charge de l'anémie ferriprive : fer oral ou IV ?",
    'Antidépresseurs chez le sujet âgé : lesquels privilégier ?',
    "Gestion d'un INR à 6 asymptomatique sous AVK ?",
    "Critères d'hospitalisation d'une pneumonie aiguë communautaire ?",
    "Traitement de l'ostéoporose post-fracture : quelle séquence ?",
    "Surveillance d'un patient sous amiodarone : quel bilan ?",
    'CAT devant une élévation isolée des gamma-GT ?',
    'Place des anticoagulants oraux directs dans le SAPL ?',
    'Désescalade antibiotique : quels critères de réévaluation à 48-72 h ?',
    'Dépistage de la BPCO chez le fumeur asymptomatique : pour qui ?',
    "Quand introduire un antagoniste des récepteurs minéralocorticoïdes dans l'IC ?",
    'Hypothyroïdie fruste : qui traiter ?',
    "Bilan d'extension d'un mélanome selon l'indice de Breslow ?",
    'Conduite à tenir devant une neutropénie fébrile ?',
    'Metformine et produit de contraste iodé : que faire en pratique ?',
    "Prise en charge d'une crise de goutte sous anticoagulants ?",
    'Interaction ISRS + tramadol : quel risque et quelle conduite ?',
    "Quand prescrire une MAPA plutôt qu'une automesure tensionnelle ?",
    "Antibioprophylaxie de l'endocardite : indications actuelles ?",
    'CAT devant une microalbuminurie chez le diabétique de type 2 ?',
    'Sevrage des benzodiazépines chez le sujet âgé : quel protocole ?',
    'Place des gliflozines dans la maladie rénale chronique ?',
    'Suspicion de DRESS syndrome : quels critères diagnostiques ?',
    "Réévaluation d'une ordonnance polymédiquée : par où commencer ?",
  ],
};

/**
 * Fenêtre de `count` questions pour un tick de rotation donné.
 * Avance de `count` questions par tick et boucle sur la liste (wrap-around),
 * de sorte que toutes les questions finissent par être montrées.
 */
export function suggestionWindow(list: string[], tick: number, count = SUGGESTIONS_VISIBLE_COUNT): string[] {
  if (list.length === 0) return [];
  const size = Math.min(count, list.length);
  const start = ((tick * size) % list.length + list.length) % list.length;
  return Array.from({ length: size }, (_, i) => list[(start + i) % list.length]);
}
