-- Migration 0037 — Corpus ECOS « Annales 2024 » (stations pédagogiques fictives).
--
-- Ajoute 15 stations d'ECOS ORIGINALES et FICTIVES couvrant les situations de départ
-- (SDD) du programme officiel EDN travaillées dans les annales ECOS 2024. Aucune donnée de
-- santé réelle ni contenu tiers copyrighté : les vignettes, fiches de rôle patient et grilles
-- de correction sont rédigées de zéro (mêmes garanties que le seed 0013). Miroir de
-- data/ecos-cases.json (source de vérité du seed scripts/seed-ecos-cases.mjs).
--
-- Idempotent : ON CONFLICT (slug) met à jour le contenu sans casser l'existant. RLS inchangée
-- (lecture publique des cas publiés, écriture service_role — cf 0013). Aucun schéma modifié.

insert into public.ecos_cases (slug, title, specialty, level, duration_minutes, brief, patient_profile, grading_grid, is_published)
values
  (
    $sl$douleur-abdominale-fosse-iliaque$sl$,
    $ti$Douleur de la fosse iliaque droite fébrile$ti$,
    $sp$Chirurgie digestive · Imagerie$sp$,
    $lv$DFASM$lv$,
    10,
    $br$M. Camille Renaud, 22 ans, se présente aux urgences pour une douleur de la fosse iliaque droite depuis 24 heures. Menez l'interrogatoire, orientez le diagnostic et justifiez l'examen d'imagerie que vous demandez.$br$,
    $pp${"role_brief":"Tu joues Camille Renaud, 22 ans, étudiant(e), sans antécédent.\nSYMPTÔMES : douleur qui a commencé autour du nombril hier, puis s'est déplacée et fixée en bas à droite du ventre depuis ce matin, continue, 6/10, aggravée quand tu marches ou que la voiture passe sur un dos d'âne. Tu n'as pas faim (dégoût), tu as eu une nausée, pas de vomissement. Fièvre ressentie hier soir.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : pas de troubles urinaires (si on demande), pas de diarrhée ni de sang dans les selles (si on demande), dernières règles il y a 2 semaines pour un profil féminin (si on demande la possibilité d'une grossesse : tu réponds que c'est peu probable, pas de rapport récent), température prise à la maison 38,3°C (seulement si on te demande si tu as pris ta température).\nCOMPORTEMENT : tu réponds UNE information à la fois, précisément à la question posée. Tu ne listes jamais spontanément tes symptômes ni tes antécédents. Tu ne connais pas le diagnostic. Langage courant, pas de mot médical.\nSI L'ÉTUDIANT DEMANDE L'EXAMEN CLINIQUE (palpation, défense) : tu dis que ça fait très mal quand il appuie en bas à droite et encore plus quand il relâche."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Douleur de la FID fébrile\n\n**Interrogatoire (5 pts)**\n- Caractérise la douleur : début péri-ombilical puis migration en FID /1\n- Chronologie, intensité, facteurs aggravants (ébranlement) /1\n- Signes digestifs : anorexie, nausées, transit /1\n- Fièvre recherchée activement /1\n- Chez une femme : recherche systématique d'une grossesse et de signes gynécologiques /1\n\n**Raisonnement diagnostique (5 pts)**\n- Évoque une appendicite aiguë en priorité /2\n- Diagnostics différentiels pertinents (adénolymphite, colique néphrétique, pathologie gynéco/GEU si femme) /2\n- Reconnaît le caractère potentiellement chirurgical / urgent /1\n\n**Examens complémentaires (4 pts)**\n- Biologie : NFS, CRP, βhCG chez la femme, BU /2\n- Imagerie justifiée : échographie abdominale en 1re intention (sujet jeune/mince), TDM abdomino-pelvienne si doute ou échographie non contributive /2\n\n**Communication (3 pts)**\n- Explique la démarche et le motif de l'imagerie /1\n- Informe de l'éventualité d'une prise en charge chirurgicale /1\n- Attitude empathique, patient laissé à jeun /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$anomalie-examen-mammaire$sl$,
    $ti$Découverte d'un nodule du sein$ti$,
    $sp$Gynécologie · Sénologie$sp$,
    $lv$DFASM$lv$,
    10,
    $br$Mme Farida Benali, 54 ans, consulte car elle a senti une « boule » dans le sein droit. Menez l'interrogatoire et l'orientation diagnostique, et expliquez-lui la suite de la prise en charge.$br$,
    $pp${"role_brief":"Tu joues Mme Farida Benali, 54 ans, ménopausée depuis 3 ans.\nMOTIF : tu as senti par hasard une boule dans le sein droit il y a environ 3 semaines en te douchant. Elle ne fait pas mal.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : la boule n'a pas changé de taille selon toi ; pas d'écoulement du mamelon (si on demande) ; pas de rougeur ni de peau d'orange (si on demande) ; tu n'as jamais fait de mammographie de dépistage (tu as zappé les courriers) ; ta mère a eu un cancer du sein à 60 ans (seulement si on demande les antécédents familiaux) ; pas de traitement hormonal ; premières règles à 12 ans, une grossesse à 33 ans.\nCOMPORTEMENT : tu es inquiète mais tu réponds calmement, une info à la fois, uniquement à ce qu'on te demande. Tu ne déballes pas tes antécédents spontanément. Si on t'annonce qu'il faut des examens, tu demandes « est-ce que c'est grave, docteur ? ».\nTu ne connais pas le diagnostic. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Anomalie de l'examen mammaire\n\n**Interrogatoire (5 pts)**\n- Caractérise la tuméfaction : ancienneté, évolution, douleur /1\n- Signes associés : écoulement mamelonnaire, modifications cutanées, adénopathie /1\n- Facteurs de risque : âge, antécédent familial de cancer du sein/ovaire /1\n- Antécédents gynéco-obstétricaux (ménarche, ménopause, parité, THM) /1\n- Statut vis-à-vis du dépistage organisé /1\n\n**Raisonnement (4 pts)**\n- Évoque en priorité un cancer du sein devant tout nodule chez une femme ménopausée /2\n- Ne se laisse pas rassurer faussement par l'absence de douleur /1\n- Reconnaît le caractère systématique du bilan (triple test) /1\n\n**Prise en charge diagnostique (4 pts)**\n- Examen clinique des deux seins et des aires ganglionnaires /1\n- Imagerie : mammographie bilatérale + échographie mammaire /2\n- Prélèvement (microbiopsie) pour preuve histologique /1\n\n**Communication / annonce (3 pts)**\n- Ne banalise ni ne dramatise ; annonce d'une démarche, pas d'un diagnostic /1\n- Explique clairement les étapes à venir /1\n- Empathie, disponibilité aux questions /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$erytheme-toxidermie$sl$,
    $ti$Éruption cutanée sous antibiotique$ti$,
    $sp$Dermatologie · Pharmacovigilance$sp$,
    $lv$DFASM$lv$,
    10,
    $br$M. Théo Laurent, 28 ans, consulte pour une éruption cutanée apparue alors qu'il prend un antibiotique. Menez l'interrogatoire, recherchez des signes de gravité et proposez une conduite à tenir.$br$,
    $pp${"role_brief":"Tu joues Théo Laurent, 28 ans, sans antécédent notable.\nMOTIF : depuis 2 jours, des plaques rouges qui grattent sont apparues sur le tronc puis les bras. Tu prends de l'amoxicilline depuis 6 jours pour une angine.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : ça a commencé par le tronc ; ça gratte (prurit) ; tu n'as pas de fièvre aujourd'hui mais tu avais 38°C hier (si on demande) ; pas de cloques ni de décollement de la peau (si on demande) ; pas de douleur ni de brûlure dans la bouche ou les yeux (si on demande) ; pas de gonflement du visage ni de gêne pour respirer (si on demande) ; tu n'as jamais eu de réaction à un médicament avant ; tu ne prends aucun autre médicament.\nCOMPORTEMENT : tu réponds une chose à la fois, uniquement à la question posée, sans énumérer. Tu ne connais pas le diagnostic. Si l'étudiant demande à examiner : décris des plaques rouges en relief sur le tronc et les bras, sans atteinte du visage, sans bulle.\nLangage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Toxidermie sous amoxicilline\n\n**Interrogatoire (5 pts)**\n- Chronologie précise : délai prise du médicament / éruption /1\n- Médicament(s) en cause et autres prises récentes /1\n- Description de l'éruption (type, topographie, prurit) /1\n- Recherche de fièvre et d'altération de l'état général /1\n- Antécédents d'allergie médicamenteuse /1\n\n**Recherche de signes de gravité (5 pts)**\n- Atteinte muqueuse (buccale, oculaire, génitale) /1\n- Décollement cutané / signe de Nikolsky / bulles (Stevens-Johnson, Lyell) /1\n- Œdème du visage, dysphagie, dyspnée (anaphylaxie/angio-œdème) /1\n- Signes de DRESS : fièvre élevée, œdème du visage, adénopathies /1\n- Conclut ici à une toxidermie bénigne (exanthème maculo-papuleux) sans signe de gravité /1\n\n**Conduite à tenir (4 pts)**\n- Arrêt immédiat et définitif de l'antibiotique suspect /2\n- Contre-indication notée, information et déclaration de pharmacovigilance /1\n- Traitement symptomatique (antihistaminique, émollients), consignes de reconsultation en cas d'aggravation /1\n\n**Communication (1 pt)**\n- Explique l'importance d'éviter ce médicament à l'avenir /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$chute-personne-agee$sl$,
    $ti$Chute d'une personne âgée polymédiquée$ti$,
    $sp$Gériatrie$sp$,
    $lv$DFASM$lv$,
    10,
    $br$Mme Odette Girard, 82 ans, consulte avec sa fille après une chute à domicile. Recherchez les causes et les facteurs de risque de chute, et évaluez son ordonnance.$br$,
    $pp${"role_brief":"Tu joues Mme Odette Girard, 82 ans, veuve, vivant seule à domicile. Réponses parfois lentes.\nMOTIF : tu es tombée hier dans le salon. Ta fille a insisté pour que tu consultes.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : tu t'es sentie « partir », un peu étourdie en te levant du fauteuil (hypotension orthostatique) ; pas de perte de connaissance selon toi ; tu ne t'es pas mordu la langue, pas de perte d'urine (si on demande) ; tu as pu te relever seule après quelques minutes ; tu prends beaucoup de médicaments : pour la tension, pour dormir (un somnifère depuis des années), pour le cœur, et récemment un nouveau comprimé pour la tension ajouté par le cardiologue (si on demande l'ordonnance) ; tu portes des lunettes mais elles datent ; il y a des tapis dans le salon ; tu vas moins bien aux toilettes la nuit ; tu manges peu.\nCOMPORTEMENT : tu réponds à une question à la fois, sans tout raconter d'un coup. Tu minimises (« ce n'est rien »). Tu ne connais pas la cause. Langage courant de personne âgée."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Chute de la personne âgée\n\n**Analyse de la chute (4 pts)**\n- Circonstances et lieu de la chute /1\n- Recherche d'un malaise / perte de connaissance / prodromes (orthostatisme) /1\n- Recherche de signes en faveur d'une cause cardiaque ou neurologique /1\n- Conséquences de la chute (traumatisme, station au sol prolongée) /1\n\n**Facteurs de risque et cause (5 pts)**\n- Facteurs intrinsèques : âge, vue, troubles de l'équilibre, dénutrition /1\n- Facteurs extrinsèques / environnementaux (tapis, éclairage, chaussage) /1\n- Iatrogénie : revue de l'ordonnance, psychotropes/somnifère, antihypertenseurs /2\n- Identifie l'hypotension orthostatique favorisée par les traitements /1\n\n**Prise en charge (4 pts)**\n- Recherche/mesure de l'hypotension orthostatique, examen ciblé (dont ECG) /1\n- Révision thérapeutique : déprescription du somnifère, réévaluation des antihypertenseurs /2\n- Mesures de prévention (aménagement du domicile, activité physique, vitamine D, aides) /1\n\n**Communication (2 pts)**\n- Implique la patiente et sa fille sans infantiliser /1\n- Explique le caractère multifactoriel et le plan de suivi /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$prescription-transfusion$sl$,
    $ti$Prescription et sécurité transfusionnelle$ti$,
    $sp$Hématologie · Transfusion$sp$,
    $lv$DFASM$lv$,
    8,
    $br$Vous devez transfuser un concentré de globules rouges à Mme Suzanne Morel, 68 ans, hospitalisée pour une anémie mal tolérée. Expliquez-lui la procédure, recueillez son consentement et énoncez les vérifications de sécurité avant et pendant la transfusion.$br$,
    $pp${"role_brief":"Tu joues Mme Suzanne Morel, 68 ans, hospitalisée, fatiguée et essoufflée à cause d'une anémie.\nMOTIF : le médecin vient t'expliquer qu'il faut te donner du sang.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : tu n'as jamais été transfusée avant ; tu es un peu inquiète des « maladies du sang » (tu poseras la question si l'étudiant t'explique les risques) ; tu n'as pas d'objection de principe à la transfusion ; tu n'as pas d'allergie connue.\nCOMPORTEMENT : tu poses des questions simples de patiente (« Est-ce que c'est dangereux ? », « Combien de temps ça prend ? »). Tu réponds seulement à ce qu'on te demande. Tu ne connais rien à la médecine transfusionnelle : tu attends des explications claires.\nLangage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Sécurité transfusionnelle\n\n**Information et consentement (4 pts)**\n- Explique l'indication (anémie mal tolérée) en langage clair /1\n- Informe des bénéfices attendus et des risques principaux /1\n- Recueille le consentement éclairé /1\n- Répond aux inquiétudes (sécurité du don, traçabilité) /1\n\n**Examens et prescription (4 pts)**\n- Vérifie/prescrit les examens immuno-hématologiques : 2 déterminations de groupe ABO-RH + RAI valide /2\n- Prescription conforme du CGR (nombre, caractéristiques : phénotypé/irradié si indiqué) /1\n- Information/consignes de surveillance prévues /1\n\n**Sécurité au lit du patient (5 pts)**\n- Contrôle ultime pré-transfusionnel au lit du patient, par la personne qui transfuse /2\n- Concordance identité patient / documents / poche + contrôle ultime ABO (Beth-Vincent) /2\n- Surveillance : constantes avant, pendant (première 15 min) et après /1\n\n**Gestion d'un incident (2 pts)**\n- Sait arrêter immédiatement la transfusion en cas de signe d'alerte /1\n- Conserve la poche, alerte, déclare (hémovigilance) /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$douleur-abdominale-hypotension$sl$,
    $ti$Douleur abdominale avec hypotension$ti$,
    $sp$Urgences · Réanimation$sp$,
    $lv$DFASM$lv$,
    10,
    $br$M. Alain Fontaine, 61 ans, est amené aux urgences pour une douleur abdominale intense. L'infirmière vous signale une tension basse. Évaluez la gravité, orientez le diagnostic et débutez la prise en charge.$br$,
    $pp${"role_brief":"Tu joues M. Alain Fontaine, 61 ans, gros consommateur d'alcool.\nSYMPTÔMES : douleur violente en barre au niveau de l'estomac depuis ce matin, irradiant dans le dos, 9/10, tu es plié en deux, tu as vomi plusieurs fois.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : tu bois beaucoup d'alcool depuis des années (seulement si on demande précisément la consommation d'alcool) ; tu as fait un gros repas très arrosé hier soir ; tu te sens faible, la tête qui tourne quand on te redresse ; tu as soif ; pas de sang dans les vomissements (si on demande) ; pas d'antécédent chirurgical.\nCONSTANTES (à donner SEULEMENT si l'étudiant les demande, sans les interpréter) : « l'infirmière vous dit : tension 88/54, pouls 118, saturation 96%, température 37,8°C ».\nCOMPORTEMENT : tu es en souffrance, réponses courtes, une info à la fois. Tu ne minimises pas la douleur mais tu ne listes pas tes antécédents spontanément. Tu ne connais pas le diagnostic. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Douleur abdominale + hypotension\n\n**Reconnaissance de la gravité (5 pts)**\n- Prend/demande les constantes et identifie l'hypotension + tachycardie /2\n- Reconnaît un état de choc / une détresse hémodynamique /2\n- Reconnaît le caractère d'urgence vitale, alerte /1\n\n**Interrogatoire orienté (3 pts)**\n- Caractérise la douleur (barre épigastrique, irradiation dorsale) /1\n- Recherche l'intoxication alcoolique et le facteur déclenchant /1\n- Recherche des signes de gravité digestifs (hématémèse, arrêt du transit) /1\n\n**Raisonnement diagnostique (3 pts)**\n- Évoque une pancréatite aiguë (contexte alcoolique) /1\n- Diagnostics différentiels graves (ulcère perforé, ischémie mésentérique, anévrisme) /1\n- Comprend que l'hypotension impose d'éliminer une cause hémorragique/septique /1\n\n**Prise en charge initiale (4 pts)**\n- Mise en condition : 2 voies veineuses, remplissage, O2, scope, à jeun, antalgie /2\n- Bilan : NFS, ionogramme, lipasémie, bilan hépatique, gaz du sang/lactate, groupe-RAI /1\n- Imagerie adaptée (TDM abdominale) une fois stabilisé, avis réanimation/chirurgie /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$consultation-grossesse-normale$sl$,
    $ti$Consultation de grossesse normale (1er trimestre)$ti$,
    $sp$Gynécologie-obstétrique$sp$,
    $lv$DFASM$lv$,
    10,
    $br$Mme Julie Moreau, 29 ans, vient pour sa première consultation de grossesse. Elle a fait un test urinaire positif. Menez la consultation de déclaration et donnez les informations et prescriptions utiles.$br$,
    $pp${"role_brief":"Tu joues Mme Julie Moreau, 29 ans, enceinte pour la première fois, en bonne santé.\nMOTIF : ton test de grossesse est positif, tu viens voir le médecin.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : dernières règles il y a environ 8 semaines ; cycles réguliers ; tu ne prends pas d'acide folique (tu ne savais pas) ; tu fumes 5 cigarettes par jour (seulement si on demande le tabac) ; tu bois un verre de vin de temps en temps (si on demande l'alcool) ; pas de maladie chronique, pas de traitement ; tu ne sais plus si tu es à jour de tes vaccins ; tu ne connais pas ton groupe sanguin ; pas d'antécédent familial particulier ; tu te demandes si tu peux continuer le sport et ton travail.\nCOMPORTEMENT : tu es contente mais tu as plein de questions ; tu réponds à une question à la fois et tu attends les conseils. Tu ne listes pas tout spontanément. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Consultation de grossesse normale\n\n**Interrogatoire (5 pts)**\n- Datation : date des dernières règles, régularité des cycles /1\n- Antécédents médicaux, chirurgicaux, gynéco-obstétricaux /1\n- Recherche de facteurs de risque et de terrain (âge, pathologies) /1\n- Mode de vie : tabac, alcool, autres toxiques /1\n- Traitements en cours et statut vaccinal /1\n\n**Prévention et conseils (5 pts)**\n- Supplémentation en acide folique /1\n- Sevrage tabagique et arrêt de l'alcool /1\n- Règles hygiéno-diététiques, prévention de la listériose/toxoplasmose /1\n- Activité physique et travail : réassurance adaptée /1\n- Déclaration de grossesse et calendrier de suivi expliqués /1\n\n**Examens du 1er trimestre (4 pts)**\n- Bilan biologique obligatoire : groupe-Rhésus/RAI, sérologies (rubéole, toxo, syphilis, VIH proposé, hépatite B) /2\n- Échographie du 1er trimestre (11-13 SA + 6 j) pour datation et clarté nucale /1\n- Dépistage combiné de la trisomie 21 proposé /1\n\n**Communication (1 pt)**\n- Écoute, répond aux questions, ton rassurant et non culpabilisant /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$purpura-adulte$sl$,
    $ti$Purpura de l'adulte$ti$,
    $sp$Hématologie · Urgences$sp$,
    $lv$DFASM$lv$,
    9,
    $br$M. Kevin Dubois, 34 ans, consulte pour l'apparition de taches rouges sur les jambes. Menez l'interrogatoire, recherchez les signes de gravité et orientez la démarche diagnostique.$br$,
    $pp${"role_brief":"Tu joues Kevin Dubois, 34 ans, sans antécédent.\nMOTIF : depuis hier, des petites taches rouges sont apparues sur tes deux jambes, elles ne partent pas quand on appuie dessus.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : les taches sont surtout aux chevilles et aux jambes ; certaines sont un peu en relief (tu le diras si on te demande de décrire) ; tu n'as PAS de fièvre aujourd'hui ; pas de maux de tête ni de raideur de nuque (si on demande) ; tu te sens bien par ailleurs ; tu as eu un rhume la semaine dernière ; pas de saignement des gencives ni du nez (si on demande) ; tu ne prends pas de médicament ; pas de voyage récent.\nCOMPORTEMENT : tu réponds une info à la fois, uniquement à la question. Tu ne sais pas ce que c'est. Si l'étudiant veut examiner : décris un purpura pétéchial et un peu infiltré des membres inférieurs, symétrique, sans autre lésion.\nLangage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Purpura de l'adulte\n\n**Reconnaissance et description (3 pts)**\n- Confirme le purpura (ne s'efface pas à la vitropression) /1\n- Décrit le type (pétéchial, ecchymotique, infiltré/vasculaire) et la topographie /1\n- Distingue purpura plaquettaire vs vasculaire /1\n\n**Recherche des signes de gravité — URGENCE (4 pts)**\n- Recherche fièvre + syndrome méningé (purpura fulminans = urgence absolue) /2\n- Recherche un syndrome hémorragique muqueux (bulles, épistaxis, gingivorragies) /1\n- Recherche une altération de l'état général, extension rapide /1\n\n**Démarche diagnostique (4 pts)**\n- Interrogatoire : contexte infectieux, médicaments, terrain /1\n- Oriente : purpura vasculaire (vascularite/IgA post-infectieux ici) vs thrombopénique /1\n- Biologie : NFS-plaquettes en urgence, bilan d'hémostase, CRP /2\n\n**Conduite et communication (2 pts)**\n- Sait que fièvre + purpura extensif impose antibiothérapie immédiate et SAMU /1\n- Explique la démarche et la surveillance /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$douleur-thoracique-suspicion-ep$sl$,
    $ti$Douleur thoracique et demande d'imagerie$ti$,
    $sp$Pneumologie · Cardiologie$sp$,
    $lv$DFASM$lv$,
    10,
    $br$Mme Nadia Cherif, 41 ans, consulte pour une douleur thoracique et un essoufflement apparus brutalement. Menez l'interrogatoire, évaluez la probabilité clinique et justifiez la stratégie d'imagerie.$br$,
    $pp${"role_brief":"Tu joues Mme Nadia Cherif, 41 ans.\nSYMPTÔMES : depuis ce matin, une douleur dans le côté droit de la poitrine qui augmente quand tu respires à fond, et tu es essoufflée quand tu marches.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : tu rentres d'un long voyage en avion il y a 2 jours (seulement si on demande un voyage/immobilisation) ; tu prends la pilule (seulement si on demande la contraception) ; tu fumes (si on demande) ; ta jambe droite (mollet) est un peu gonflée et douloureuse depuis hier (seulement si on demande d'examiner les jambes ou s'il y a une douleur de mollet) ; pas de fièvre ; pas de crachats de sang (si on demande) ; pas d'antécédent.\nCONSTANTES (SEULEMENT si demandées, sans interprétation) : « pouls 104, saturation 93% en air ambiant, tension 124/78, température 37,2°C, fréquence respiratoire 22 ».\nCOMPORTEMENT : tu réponds une info à la fois, précisément. Tu ne connais pas le diagnostic. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Suspicion d'embolie pulmonaire\n\n**Interrogatoire (5 pts)**\n- Caractérise la douleur (pleurale) et la dyspnée /1\n- Recherche des facteurs de risque de MTEV : voyage/immobilisation, œstroprogestatifs, tabac /2\n- Recherche des signes de TVP (douleur/œdème du mollet) /1\n- Recherche des signes de gravité (syncope, hémoptysie, malaise) /1\n\n**Raisonnement / probabilité (4 pts)**\n- Évoque l'embolie pulmonaire en priorité /2\n- Évalue la probabilité clinique (score de Wells ou Genève) /1\n- Diagnostics différentiels (SCA, pneumopathie, pneumothorax) /1\n\n**Stratégie d'examens (4 pts)**\n- ECG + gaz du sang + radiographie thoracique de débrouillage /1\n- Adapte à la probabilité : D-dimères si probabilité faible/intermédiaire /1\n- Angioscanner thoracique (ou scintigraphie V/Q) si D-dimères positifs ou probabilité forte /2\n\n**Communication (2 pts)**\n- Explique la démarche et l'urgence /1\n- Attitude rassurante et claire /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$anemie-melena-rectorragie$sl$,
    $ti$Anémie et saignement digestif$ti$,
    $sp$Hépato-gastro-entérologie$sp$,
    $lv$DFASM$lv$,
    10,
    $br$M. Robert Lemoine, 67 ans, est adressé pour une fatigue et une baisse de l'hémoglobine découverte sur un bilan. Menez l'interrogatoire, recherchez une hémorragie digestive et proposez la démarche diagnostique.$br$,
    $pp${"role_brief":"Tu joues M. Robert Lemoine, 67 ans, retraité.\nMOTIF : ton médecin a trouvé que tu manquais de sang sur une prise de sang et t'a envoyé consulter. Tu es fatigué et essoufflé à l'effort depuis quelques semaines.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : tu as remarqué des selles noires, très foncées et malodorantes depuis une dizaine de jours (SEULEMENT si on demande l'aspect des selles ou la présence de sang) ; pas de sang rouge visible ; tu as un peu maigri (3-4 kg) sans le vouloir ; tu prends de l'aspirine pour le cœur (si on demande les médicaments) ; tu ne bois pas beaucoup ; ton père est mort d'un cancer du côlon (si on demande les antécédents familiaux) ; tu n'as jamais fait de coloscopie ni le test de dépistage.\nEXAMEN (si l'étudiant propose un toucher rectal) : « au toucher rectal, présence de selles noires sur le doigtier, pas de masse palpable ».\nCOMPORTEMENT : tu minimises, tu réponds une info à la fois. Tu ne fais pas le lien toi-même. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Anémie et hémorragie digestive\n\n**Interrogatoire (5 pts)**\n- Signes d'anémie (asthénie, dyspnée d'effort, pâleur) /1\n- Recherche active d'un saignement extériorisé : méléna, rectorragie /2\n- Signes d'alarme : amaigrissement, altération de l'état général /1\n- Facteurs favorisants : AINS/aspirine/anticoagulant, alcool, antécédents /1\n\n**Raisonnement (4 pts)**\n- Relie l'anémie à une hémorragie digestive chronique (anémie ferriprive) /1\n- Évoque une cause haute (ulcère, œsophagite) et basse (cancer colorectal) /1\n- Devant l'âge, l'amaigrissement et l'antécédent familial, évoque le cancer colorectal /1\n- Réalise/propose le toucher rectal /1\n\n**Examens (4 pts)**\n- NFS, ferritinémie, bilan martial, groupe-RAI /1\n- Endoscopies : fibroscopie œso-gastro-duodénale ET coloscopie /2\n- Évalue la tolérance et le retentissement (transfusion si mal toléré) /1\n\n**Communication (2 pts)**\n- Explique la nécessité des endoscopies sans dramatiser /1\n- Empathie, réponses aux inquiétudes /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$interpretation-hemogramme$sl$,
    $ti$Interprétation d'un hémogramme anormal$ti$,
    $sp$Médecine interne · Hématologie$sp$,
    $lv$DFASM$lv$,
    8,
    $br$Mme Christine Aubert, 63 ans, vient chercher les résultats d'une prise de sang demandée pour une fatigue et des douleurs osseuses. Interprétez l'hémogramme, synthétisez les anomalies et expliquez la suite.$br$,
    $pp${"role_brief":"Tu joues Mme Christine Aubert, 63 ans, qui vient pour ses résultats.\nMOTIF : tu es fatiguée depuis des mois et tu as mal au dos et aux côtes.\nRÉSULTATS À COMMUNIQUER SEULEMENT SI L'ÉTUDIANT DEMANDE À VOIR LA PRISE DE SANG (tu lis les chiffres sans les interpréter) : « Hémoglobine 9,2 g/dL, VGM 92 fL, plaquettes 210 G/L, globules blancs 6 G/L normaux ; à la biochimie : protéines totales élevées à 95 g/L, calcium élevé à 2,9 mmol/L, créatinine augmentée à 145 µmol/L. »\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : douleurs osseuses du dos et des côtes ; tu bois beaucoup et tu urines beaucoup (si on demande) ; pas de fièvre ; pas de saignement ; tu as eu récemment une infection pulmonaire.\nCOMPORTEMENT : tu apportes les résultats mais tu ne les comprends pas ; tu réponds à une question à la fois. Tu attends les explications. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Interprétation d'un hémogramme\n\n**Lecture et synthèse des résultats (5 pts)**\n- Identifie l'anémie normocytaire /1\n- Repère l'hyperprotidémie (pic ?) /1\n- Repère l'hypercalcémie /1\n- Repère l'insuffisance rénale /1\n- Fait la synthèse : association évocatrice (anémie + hyperprotidémie + hypercalcémie + IR + douleurs osseuses) /1\n\n**Raisonnement diagnostique (4 pts)**\n- Évoque un myélome multiple /2\n- Interprète l'hyperprotidémie comme une immunoglobuline monoclonale possible /1\n- Relie les douleurs osseuses aux lésions lytiques /1\n\n**Démarche complémentaire (3 pts)**\n- Électrophorèse des protéines sériques + immunofixation /1\n- Bilan : protéinurie de Bence-Jones, imagerie osseuse, myélogramme /1\n- Prise en charge de l'hypercalcémie et de l'IR si sévères /1\n\n**Communication (3 pts)**\n- Explique les anomalies en langage simple /1\n- Annonce une démarche diagnostique, pas un diagnostic définitif /1\n- Empathie, disponibilité /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$nausees-vomissements$sl$,
    $ti$Nausées et vomissements$ti$,
    $sp$Médecine générale · HGE$sp$,
    $lv$DFASM$lv$,
    9,
    $br$Mme Émilie Rousseau, 26 ans, consulte pour des nausées et des vomissements évoluant depuis 3 jours. Menez l'interrogatoire, recherchez des signes de gravité et orientez le diagnostic.$br$,
    $pp${"role_brief":"Tu joues Mme Émilie Rousseau, 26 ans.\nMOTIF : tu as la nausée et tu vomis depuis 3 jours, tu n'arrives presque plus à manger.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : les vomissements sont alimentaires puis bilieux, plutôt le matin ; pas de sang dedans (si on demande) ; tu n'as pas mal à la tête de façon importante ; tes dernières règles remontent à 7 semaines (SEULEMENT si on te demande la date des règles ou une possible grossesse) ; tu as des rapports sans contraception régulière ; pas de fièvre ; pas de diarrhée ; tu urines peu et tu as la bouche sèche depuis hier (signes de déshydratation, si on demande) ; pas de médicament ; pas de voyage.\nCOMPORTEMENT : tu réponds une info à la fois, précisément à la question. Tu ne penses pas spontanément à une grossesse. Tu ne connais pas la cause. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Nausées et vomissements\n\n**Interrogatoire (5 pts)**\n- Caractérise les vomissements : ancienneté, horaire, contenu, abondance /1\n- Signes digestifs associés (douleur, transit, hématémèse) /1\n- Recherche systématique d'une grossesse chez une femme en âge de procréer /2\n- Recherche de causes (médicaments, toxique, contexte infectieux, neurologique) /1\n\n**Recherche de signes de gravité (4 pts)**\n- Signes de déshydratation (soif, oligurie, muqueuses sèches, pli cutané) /2\n- Signes neurologiques (céphalées, syndrome méningé, HTIC) /1\n- Retentissement / intolérance alimentaire totale /1\n\n**Diagnostic et prise en charge (3 pts)**\n- Évoque une grossesse (vomissements gravidiques) parmi les hypothèses prioritaires /1\n- Prescrit βhCG et ionogramme, adapte le bilan au contexte /1\n- Traitement symptomatique (réhydratation, antiémétique compatible) /1\n\n**Communication (3 pts)**\n- Interroge sans jugement /1\n- Explique la démarche /1\n- Consignes de reconsultation /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$bradycardie-malaise$sl$,
    $ti$Bradycardie et malaise$ti$,
    $sp$Cardiologie · Urgences$sp$,
    $lv$DFASM$lv$,
    9,
    $br$M. Georges Petit, 74 ans, consulte après plusieurs malaises. L'infirmière note un pouls lent. Menez l'interrogatoire, demandez l'ECG et proposez votre conduite à tenir.$br$,
    $pp${"role_brief":"Tu joues M. Georges Petit, 74 ans, hypertendu.\nMOTIF : tu as fait deux malaises cette semaine, avec une impression de voile noir, une fois tu es tombé.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : les malaises surviennent brutalement, sans prévenir, parfois assis ; tu reviens à toi tout de suite ; pas de mouvements anormaux ni de morsure de langue (si on demande) ; tu te sens fatigué et essoufflé depuis quelques jours ; tu prends un médicament pour le cœur/ralentir le pouls (bêtabloquant) et un pour la tension (si on demande l'ordonnance) ; le cardiologue a récemment augmenté une dose.\nECG (à communiquer SEULEMENT si l'étudiant le demande, sans l'interpréter à sa place) : « l'ECG montre un rythme lent à 38/min, avec des ondes P qui ne sont pas toujours suivies d'un complexe (dissociation) ».\nCONSTANTES si demandées : « pouls 38, tension 105/60, saturation 97% ».\nCOMPORTEMENT : tu réponds une info à la fois. Tu ne connais pas la cause. Langage courant de personne âgée."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Bradycardie et malaise\n\n**Interrogatoire (4 pts)**\n- Caractérise les malaises (brutalité, prodromes, perte de connaissance, récupération) /2\n- Élimine une crise convulsive (morsure, mouvements, confusion post-critique) /1\n- Recherche l'iatrogénie : bêtabloquant, anti-arythmique, digitalique /1\n\n**Examen et ECG (4 pts)**\n- Prend les constantes, confirme la bradycardie /1\n- Demande un ECG en urgence /1\n- Interprète : bradycardie + BAV de haut degré (ondes P bloquées) /2\n\n**Raisonnement et gravité (3 pts)**\n- Relie syncopes et trouble conductif (syncope d'Adams-Stokes) /1\n- Reconnaît le risque vital (asystolie) et l'urgence /1\n- Recherche une cause réversible (médicament, hyperkaliémie, ischémie) /1\n\n**Conduite à tenir (4 pts)**\n- Scope, voie veineuse, surveillance continue /1\n- Arrêt des médicaments bradycardisants, correction d'une cause /1\n- Atropine si mal toléré ; avis cardiologique urgent /1\n- Orientation vers entraînement électrosystolique / pacemaker /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$prevention-cardiovasculaire$sl$,
    $ti$Prévention chez un patient à risque cardiovasculaire$ti$,
    $sp$Cardiologie · Prévention$sp$,
    $lv$DFASM$lv$,
    9,
    $br$M. Pascal Giraud, 52 ans, vient en consultation de suivi après un infarctus du myocarde survenu il y a 6 mois. Faites le point sur ses facteurs de risque, son traitement et l'éducation à la prévention secondaire.$br$,
    $pp${"role_brief":"Tu joues M. Pascal Giraud, 52 ans, commercial, qui a fait un infarctus il y a 6 mois (stent posé).\nMOTIF : consultation de suivi.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : tu as recommencé à fumer (10/j) « à cause du stress » (SEULEMENT si on demande le tabac) ; tu prends tes médicaments mais tu oublies souvent celui du cholestérol et tu as arrêté l'un d'eux car il te fatiguait (si on demande l'observance) ; tu ne fais pas de sport ; tu manges beaucoup de plats préparés ; tu ne connais pas tes derniers chiffres de cholestérol ; ton travail est stressant ; pas de douleur thoracique récente ; pas d'essoufflement anormal.\nCOMPORTEMENT : tu minimises un peu, tu réponds à une question à la fois. Tu attends des conseils concrets. Langage courant."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Prévention cardiovasculaire secondaire\n\n**Bilan des facteurs de risque (4 pts)**\n- Tabac : recherche de la reprise, évaluation de la dépendance /1\n- Alimentation, activité physique, surpoids /1\n- Recherche des autres FDR : HTA, diabète, dyslipidémie, hérédité /1\n- Recherche de symptômes de récidive (angor, dyspnée) /1\n\n**Évaluation du traitement (4 pts)**\n- Vérifie l'observance et connaît le traitement post-IDM (antiagrégant(s), statine, IEC/ARA2, bêtabloquant) /2\n- Repère l'arrêt/oubli de traitements et en explore la raison /1\n- Sécurise la reprise (ne pas arrêter l'antiagrégant, gérer l'effet indésirable) /1\n\n**Éducation et objectifs (4 pts)**\n- Sevrage tabagique : proposition d'accompagnement /1\n- Règles hygiéno-diététiques et activité physique adaptée (réadaptation) /1\n- Objectif de LDL-cholestérol bas en prévention secondaire /1\n- Contrôle des chiffres tensionnels et glycémiques /1\n\n**Communication (3 pts)**\n- Entretien motivationnel, sans culpabiliser /1\n- Objectifs concrets et partagés /1\n- Planifie le suivi /1"}$gg$::jsonb,
    true
  ),
  (
    $sl$lombalgie-arret-travail$sl$,
    $ti$Lombalgie aiguë et arrêt de travail$ti$,
    $sp$Rhumatologie · Médecine générale$sp$,
    $lv$DFASM$lv$,
    9,
    $br$M. Sébastien Marchand, 38 ans, manutentionnaire, consulte pour une douleur lombaire aiguë survenue en portant une charge. Menez l'interrogatoire, recherchez des signes d'alarme et discutez la prise en charge, y compris l'arrêt de travail.$br$,
    $pp${"role_brief":"Tu joues Sébastien Marchand, 38 ans, manutentionnaire dans un entrepôt.\nMOTIF : hier en portant un carton lourd, tu as ressenti un blocage en bas du dos ; depuis, tu as très mal et du mal à bouger.\nÉLÉMENTS À NE RÉVÉLER QUE SI ON POSE LA QUESTION PRÉCISE : la douleur reste dans le bas du dos, elle ne descend PAS dans la jambe (si on demande une irradiation) ; pas de fourmillements ni de faiblesse dans les jambes (si on demande) ; tu contrôles bien tes urines et tes selles (si on demande, pas de troubles sphinctériens) ; pas de fièvre ; pas d'amaigrissement ; pas d'antécédent de cancer ; tu n'as pas pris de traitement ; ton travail est physique et tu es inquiet de le reprendre trop tôt ; tu voudrais un arrêt.\nCOMPORTEMENT : tu réponds une info à la fois, uniquement à ce qu'on demande. Tu ne connais pas de terme médical. Tu poses la question de l'arrêt de travail si l'étudiant n'en parle pas."}$pp$::jsonb,
    $gg${"markdown":"## Grille d'évaluation — Lombalgie aiguë et arrêt de travail\n\n**Interrogatoire (4 pts)**\n- Caractérise la douleur : circonstance (effort de soulèvement), type mécanique /1\n- Recherche une irradiation radiculaire (sciatique/cruralgie) /1\n- Contexte professionnel et gestes à risque /1\n- Antécédents et épisodes antérieurs /1\n\n**Recherche des drapeaux rouges (5 pts)**\n- Déficit neurologique moteur/sensitif des membres inférieurs /1\n- Syndrome de la queue de cheval (troubles sphinctériens, anesthésie en selle) /2\n- Fièvre, contexte infectieux /1\n- Altération de l'état général, antécédent néoplasique, douleur non mécanique /1\n\n**Prise en charge (4 pts)**\n- Conclut à une lombalgie commune sans signe de gravité → pas d'imagerie systématique /1\n- Antalgie adaptée et poursuite d'une activité physique (éviter l'alitement prolongé) /1\n- Arrêt de travail justifié, court et réévalué (métier physique) /1\n- Information : évolution favorable habituelle, conseils de prévention/gestes /1\n\n**Communication (2 pts)**\n- Rassure sur le pronostic /1\n- Décision d'arrêt expliquée et partagée /1"}$gg$::jsonb,
    true
  )
on conflict (slug) do update set
  title            = excluded.title,
  specialty        = excluded.specialty,
  level            = excluded.level,
  duration_minutes = excluded.duration_minutes,
  brief            = excluded.brief,
  patient_profile  = excluded.patient_profile,
  grading_grid     = excluded.grading_grid,
  is_published     = excluded.is_published;
